### ISSUE TITLE
update_exclusions default value incorrect

### ISSUE THREAD

**Issue by calabresemic** [edwardtfn/ha_auto_update_scheduled#1]
I found an issue with the update_exclusions default value. It is set to a Boolean false when it should be an empty list. It results in the following error when the automation is run: 

```python
ERROR (MainThread) [homeassistant.components.automation.home_assistant_auto_update_on_a_schedule_base] Error rendering variables: TypeError: argument of type 'bool' is not iterable
```

Suggest changing line 65 from
```yaml
      default: false
```
to
```yaml
      default: []
```
Appreciate all the work you've done so far!

**Comment by edwardtfn** [comment]
Fixed!
Thanks!!
